# Generated by Django 2.1.3 on 2018-12-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=150)),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now=True)),
                ('station', models.CharField(max_length=100, unique=True)),
                ('baseline', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=50)),
                ('reflector', models.BooleanField(default=True)),
            ],
        ),
    ]
